dist: xenial
matrix:
  include:        
    - language: python
      python: 
        - 3.7
      before_install:
        - cd Python
        - sudo bash "../Travis-CI/installODBC.sh"
      before_script:
        - bash ./buildandinstall.sh
        - pip install --find-links=dist sqlmlutils
      script: 
        - pytest tests/package_testing.py

notifications:
  email: false