dist: xenial
matrix:
  include:        
    - language: python
      python: 
        - 3.7
      before_install:
        - ls
        - cd Python
        - ls
      before_script:
        - sudo bash "../Travis-CI/installODBC.sh"

notifications:
  email: false