dist: xenial
matrix:
  include:        
    - language: python
      python: 
        - 3.7
      before_install:
        - cd Python
        - sudo bash "../Travis-CI/installODBC.sh"
      before_script:
        - pip install "dist/sqlmlutils-1.0.2.zip"
      script: 
        - pytest tests

notifications:
  email: false