dist: xenial
matrix:
  include:
    - language: r
      r: 
        - 3.5
      cache: packages
      before_install:
        - cd R
        - ls
      before_script:
        - sudo bash "../Travis-CI/installODBC.sh"
        
    - language: python
      python: 
        - 3.7
      before_install:
        - cd python
        - ls
      before_script:
        - sudo bash "../Travis-CI/installODBC.sh"

notifications:
  email: false